config { type: "assertion" }


WITH ranked AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY transaction_id, date, product_category, CAST(quantity AS STRING), CAST(unit_price AS STRING), CAST(transaction_amt AS STRING)
      ORDER BY date
    ) AS row_num
  FROM ${ref("sales_gold")}
)
SELECT
  date,
  transaction_id,
  product_category,
  quantity,
  unit_price,
  transaction_amt
FROM ranked
WHERE row_num > 1

